### ISSUE TITLE
2.12 support

### ISSUE THREAD

**Issue by fomkin** [Verizon/delorean#1]

**Comment by timperrett** [comment]
@fomkin we wont be migrating internally to 2.12 for some time, but adjusting the build to support 2.12 should be fairly trivial, so please have a go and send a PR if you need 2.12 support :-) Cheers

**Comment by fomkin** [comment]
@timperrett I wish I could, but project depends on your sbt-rig which is not support 2.12.

**Comment by timperrett** [comment]
@fomkin ah so you are using sbt-rig on your own open source project? Updating that to use 2.12 should be a couple of lines of change, and lining up the scalatest versions. As I mentioned, we don't have direct 2.12 needs in the short term, and the holidays are a tough time for engineering staff as its a skeleton crew, so doing anything this quarter is unlikely from us. 

If you want to give making that change a go, i'll happy review, advise and steward the change into master :-) 

Best,

Tim

**Comment by fomkin** [comment]
@timperrett  
> ah so you are using sbt-rig on your own open source project?

I mean delorean is dependent on sbt-rig. I use delorean here http://github.com/fomkin/korolev.

**Comment by timperrett** [comment]
@fomkin sbt-rig had 2.12 support added to it by @reactormonk recently, so do checkout the latest version. Should be easy to update the build matrix with the needed changes.

**Comment by fomkin** [comment]
@timperrett yes I know, thank you. I already did it Verizon/delorean#2. But I face with problem Verizon/sbt-rig#4 (possible solution Verizon/sbt-rig#5)
